all:
  vars:
    # GKE cluster variables
    gcp_project: ascn-grupo30
    gcp_auth_kind: serviceaccount
    gcp_cred_file: inventory/ascn-grupo30-final.json
    gcp_zone: us-central1-a
    gcp_image_type: ubuntu_containerd
    gcp_machine_type: e2-highcpu-4
    gcp_disk_size_gb: 20              # Can be changed if necessary
    gcp_initial_node_count: 2 
    
    # APP variables
    app_ip: "34.122.55.133"
    app_port: 8000
