apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 8000
      nodePort: 30062
  type: LoadBalancer
