apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
  - port: 6379  # Redis default port
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP  # Use ClusterIP to expose Redis internally within the cluster
